version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: newsdb
      POSTGRES_USER: newsuser
      POSTGRES_PASSWORD: newspass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    environment:
      DATABASE_URL: postgresql://newsuser:newspass@postgres:5432/newsdb
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: sh -c "npm run migrate && npm start"

volumes:
  postgres_data: 